"""
NeuralForge — Production Code Generator Service
Generates ready-to-use production code for multiple deployment targets:
Python, FastAPI, Flask, Streamlit, Docker, and Cloud (AWS/GCP/Azure/HuggingFace).
"""

import logging
from typing import Dict, Optional

logger = logging.getLogger("neuralforge.production_codegen")


class ProductionCodegenService:
    """Generates production-ready inference and deployment code."""

    @staticmethod
    def generate(
        target: str, model_format: str, model_name: str,
        task_type: str, feature_names: list = None, target_column: str = None,
        num_features: int = None,
    ) -> Dict[str, str]:
        """
        Generate production code for a given deployment target.
        Returns dict with 'code', 'filename', 'language' keys.
        """
        generators = {
            "python": ProductionCodegenService._gen_python,
            "fastapi": ProductionCodegenService._gen_fastapi,
            "flask": ProductionCodegenService._gen_flask,
            "streamlit": ProductionCodegenService._gen_streamlit,
            "docker": ProductionCodegenService._gen_docker,
            "aws": ProductionCodegenService._gen_aws_lambda,
            "gcp": ProductionCodegenService._gen_gcp_cloudrun,
            "azure": ProductionCodegenService._gen_azure_functions,
            "huggingface": ProductionCodegenService._gen_huggingface_spaces,
        }
        gen = generators.get(target.lower())
        if not gen:
            return {
                "code": f"# Code generation for target '{target}' is not supported yet.",
                "filename": "unsupported.py",
                "language": "python",
            }
        return gen(model_format, model_name, task_type, feature_names, target_column, num_features)

    @staticmethod
    def get_available_targets() -> list:
        """Return list of available deployment targets."""
        return [
            {"id": "python", "label": "Python Script", "icon": "🐍", "description": "Raw prediction script"},
            {"id": "fastapi", "label": "FastAPI Server", "icon": "⚡", "description": "High-performance async REST API"},
            {"id": "flask", "label": "Flask Server", "icon": "🌶️", "description": "Lightweight REST API"},
            {"id": "streamlit", "label": "Streamlit App", "icon": "🎈", "description": "Interactive ML web app"},
            {"id": "docker", "label": "Docker", "icon": "🐳", "description": "Containerized deployment"},
            {"id": "aws", "label": "AWS Lambda", "icon": "☁️", "description": "Serverless on AWS"},
            {"id": "gcp", "label": "GCP Cloud Run", "icon": "☁️", "description": "Serverless on Google Cloud"},
            {"id": "azure", "label": "Azure Functions", "icon": "☁️", "description": "Serverless on Azure"},
            {"id": "huggingface", "label": "HuggingFace Spaces", "icon": "🤗", "description": "Deploy to HuggingFace"},
        ]

    # ── Python ─────────────────────────────────────────────────

    @staticmethod
    def _gen_python(model_format, model_name, task_type, feature_names, target_column, num_features):
        features_str = ", ".join(f'"{f}"' for f in (feature_names or [f"feature_{i}" for i in range(num_features or 5)]))
        load_code = _get_load_snippet(model_format, model_name)

        code = f'''#!/usr/bin/env python3
"""
NeuralForge — Inference Script
Model: {model_name} | Format: {model_format} | Task: {task_type}
"""

{load_code}
import pandas as pd

# Load model
model = load_model("model.{model_format}")

# Example: Single prediction
sample = {{
    {", ".join(f'"{f}": 0' for f in (feature_names or [f"feature_{i}" for i in range(min(num_features or 5, 5))]))}
}}

df = pd.DataFrame([sample])
prediction = model.predict(df)
print(f"Prediction: {{prediction[0]}}")

# With probability (if supported)
if hasattr(model, "predict_proba"):
    proba = model.predict_proba(df)
    print(f"Confidence: {{max(proba[0]) * 100:.1f}}%")
    print(f"Class probabilities: {{dict(zip(model.classes_, proba[0]))}}")
'''
        return {"code": code, "filename": "predict.py", "language": "python"}

    # ── FastAPI ────────────────────────────────────────────────

    @staticmethod
    def _gen_fastapi(model_format, model_name, task_type, feature_names, target_column, num_features):
        load_code = _get_load_snippet(model_format, model_name)

        code = f'''"""
NeuralForge — FastAPI Inference Server
Model: {model_name} | Task: {task_type}

Run: uvicorn api:app --host 0.0.0.0 --port 8000
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import pandas as pd
import uvicorn

{load_code}

app = FastAPI(
    title="{model_name} — Prediction API",
    description="Auto-generated by NeuralForge",
    version="1.0.0",
)

# Load model at startup
model = load_model("model.{model_format}")

class PredictionRequest(BaseModel):
    data: List[Dict[str, Any]]

class PredictionResponse(BaseModel):
    predictions: List[Any]
    probabilities: Optional[List[List[float]]] = None
    confidence: Optional[List[float]] = None

@app.post("/predict", response_model=PredictionResponse)
async def predict(request: PredictionRequest):
    """Make predictions on input data."""
    try:
        df = pd.DataFrame(request.data)
        predictions = model.predict(df).tolist()

        probabilities = None
        confidence = None
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(df)
            probabilities = proba.tolist()
            confidence = [float(max(p)) for p in proba]

        return PredictionResponse(
            predictions=predictions,
            probabilities=probabilities,
            confidence=confidence,
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.get("/health")
async def health():
    return {{"status": "healthy", "model": "{model_name}", "loaded": model is not None}}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
        return {"code": code, "filename": "api.py", "language": "python"}

    # ── Flask ──────────────────────────────────────────────────

    @staticmethod
    def _gen_flask(model_format, model_name, task_type, feature_names, target_column, num_features):
        load_code = _get_load_snippet(model_format, model_name)

        code = f'''"""
NeuralForge — Flask Inference Server
Model: {model_name} | Task: {task_type}

Run: python app.py
"""

from flask import Flask, request, jsonify
import pandas as pd

{load_code}

app = Flask(__name__)
model = load_model("model.{model_format}")

@app.route("/predict", methods=["POST"])
def predict():
    """Make predictions on input data."""
    try:
        data = request.json.get("data", [])
        if not data:
            return jsonify({{"error": "No data provided"}}), 400

        df = pd.DataFrame(data)
        predictions = model.predict(df).tolist()

        result = {{"predictions": predictions}}
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(df)
            result["probabilities"] = proba.tolist()
            result["confidence"] = [float(max(p)) for p in proba]

        return jsonify(result)
    except Exception as e:
        return jsonify({{"error": str(e)}}), 400

@app.route("/health", methods=["GET"])
def health():
    return jsonify({{"status": "healthy", "model": "{model_name}"}})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=False)
'''
        return {"code": code, "filename": "app.py", "language": "python"}

    # ── Streamlit ──────────────────────────────────────────────

    @staticmethod
    def _gen_streamlit(model_format, model_name, task_type, feature_names, target_column, num_features):
        load_code = _get_load_snippet(model_format, model_name)
        features = feature_names or [f"feature_{i}" for i in range(num_features or 5)]

        input_widgets = "\n".join([
            f'    inputs["{f}"] = st.number_input("{f}", value=0.0, key="{f}")'
            for f in features[:15]  # Limit to 15 features in the UI
        ])

        code = f'''"""
NeuralForge — Streamlit ML App
Model: {model_name} | Task: {task_type}

Run: streamlit run app.py
"""

import streamlit as st
import pandas as pd
import json

{load_code}

st.set_page_config(page_title="{model_name}", page_icon="🧠", layout="wide")

st.title("🧠 {model_name}")
st.caption("Powered by NeuralForge AutoML")

# Load model
@st.cache_resource
def get_model():
    return load_model("model.{model_format}")

model = get_model()

# --- Sidebar: Manual Input ---
st.sidebar.header("📊 Input Features")
inputs = {{}}
with st.sidebar:
{input_widgets}

# --- Main Area ---
col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("Input Data")
    df = pd.DataFrame([inputs])
    st.dataframe(df, use_container_width=True)

    if st.button("🚀 Predict", type="primary", use_container_width=True):
        prediction = model.predict(df)
        st.session_state["prediction"] = prediction[0]

        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(df)[0]
            st.session_state["confidence"] = float(max(proba))
            st.session_state["probabilities"] = proba.tolist()

with col2:
    st.subheader("Prediction Result")
    if "prediction" in st.session_state:
        st.metric("Prediction", st.session_state["prediction"])
        if "confidence" in st.session_state:
            st.metric("Confidence", f"{{st.session_state['confidence']*100:.1f}}%")
        if "probabilities" in st.session_state:
            st.bar_chart(pd.Series(st.session_state["probabilities"], name="Probability"))
    else:
        st.info("Enter features and click Predict to see results.")

# --- Batch Prediction ---
st.divider()
st.subheader("📁 Batch Prediction")
uploaded = st.file_uploader("Upload a CSV file", type=["csv"])
if uploaded:
    batch_df = pd.read_csv(uploaded)
    st.write(f"Loaded {{len(batch_df)}} rows")
    if st.button("Run Batch Prediction"):
        preds = model.predict(batch_df)
        batch_df["{target_column or 'prediction'}"] = preds
        st.dataframe(batch_df, use_container_width=True)
        st.download_button("Download Results", batch_df.to_csv(index=False), "predictions.csv")
'''
        return {"code": code, "filename": "app.py", "language": "python"}

    # ── Docker ─────────────────────────────────────────────────

    @staticmethod
    def _gen_docker(model_format, model_name, task_type, feature_names, target_column, num_features):
        safe_name = model_name.lower().replace(" ", "_").replace("-", "_")

        features = feature_names or ["feature_0", "feature_1", "feature_2"]
        sample_data = ", ".join(f'"{f}": 0' for f in features[:3])
        
        code = f'''# ============================================
# NeuralForge — Docker Deployment
# Model: {model_name}
# ============================================

# --- Dockerfile ---

FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code and model
COPY . .

EXPOSE 8000

# Run FastAPI server
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

# --- docker-compose.yml ---
# version: "3.9"
# services:
#   {safe_name}:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - MODEL_PATH=model.{model_format}
#     restart: unless-stopped

# --- Build & Run ---
# docker build -t {safe_name} .
# docker run -p 8000:8000 {safe_name}
#
# --- Test ---
# curl -X POST http://localhost:8000/predict \\
#   -H "Content-Type: application/json" \\
#   -d \'{{"data": [{{{sample_data}}}]}}\'
'''
        return {"code": code, "filename": "Dockerfile", "language": "dockerfile"}

    # ── AWS Lambda ─────────────────────────────────────────────

    @staticmethod
    def _gen_aws_lambda(model_format, model_name, task_type, feature_names, target_column, num_features):
        load_code = _get_load_snippet(model_format, model_name)

        code = f'''"""
NeuralForge — AWS Lambda Handler
Model: {model_name} | Task: {task_type}

Deploy: Package this with your model file and dependencies into a Lambda deployment package.
Use API Gateway to expose the /predict endpoint.
"""

import json
import pandas as pd

{load_code}

# Load model at cold start
model = load_model("/opt/ml/model/model.{model_format}")

def lambda_handler(event, context):
    """AWS Lambda handler for predictions."""
    try:
        body = json.loads(event.get("body", "{{}}"))
        data = body.get("data", [])

        if not data:
            return {{
                "statusCode": 400,
                "body": json.dumps({{"error": "No data provided"}})
            }}

        df = pd.DataFrame(data)
        predictions = model.predict(df).tolist()

        result = {{"predictions": predictions}}
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(df)
            result["confidence"] = [float(max(p)) for p in proba]

        return {{
            "statusCode": 200,
            "body": json.dumps(result),
            "headers": {{"Content-Type": "application/json"}}
        }}
    except Exception as e:
        return {{
            "statusCode": 500,
            "body": json.dumps({{"error": str(e)}})
        }}

# --- Deployment Instructions ---
# 1. Create a Lambda layer with your Python dependencies
# 2. Upload this file as the Lambda function handler
# 3. Set handler to: lambda_handler.lambda_handler
# 4. Configure API Gateway with POST /predict route
# 5. Set memory to at least 512 MB, timeout to 30s
'''
        return {"code": code, "filename": "lambda_handler.py", "language": "python"}

    # ── GCP Cloud Run ──────────────────────────────────────────

    @staticmethod
    def _gen_gcp_cloudrun(model_format, model_name, task_type, feature_names, target_column, num_features):
        code = f'''# ============================================
# NeuralForge — Google Cloud Run Deployment
# Model: {model_name}
# ============================================

# This uses the same FastAPI server generated above.
# Cloud Run natively supports Docker containers.

# --- Steps ---
# 1. Build the Docker image:
#    gcloud builds submit --tag gcr.io/YOUR_PROJECT_ID/{model_name.lower().replace(" ", "-")}

# 2. Deploy to Cloud Run:
#    gcloud run deploy {model_name.lower().replace(" ", "-")} \\
#      --image gcr.io/YOUR_PROJECT_ID/{model_name.lower().replace(" ", "-")} \\
#      --platform managed \\
#      --region us-central1 \\
#      --allow-unauthenticated \\
#      --memory 1Gi \\
#      --port 8000

# 3. Test:
#    curl -X POST https://YOUR_SERVICE_URL/predict \\
#      -H "Content-Type: application/json" \\
#      -d \'{{"data": [{{}}]}}\'

# --- Procfile (alternative to Docker) ---
# web: uvicorn api:app --host 0.0.0.0 --port $PORT
'''
        return {"code": code, "filename": "DEPLOY_GCP.md", "language": "markdown"}

    # ── Azure Functions ────────────────────────────────────────

    @staticmethod
    def _gen_azure_functions(model_format, model_name, task_type, feature_names, target_column, num_features):
        load_code = _get_load_snippet(model_format, model_name)

        code = f'''"""
NeuralForge — Azure Functions Handler
Model: {model_name} | Task: {task_type}
"""

import json
import logging
import azure.functions as func
import pandas as pd

{load_code}

model = load_model("model.{model_format}")

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("Prediction request received")

    try:
        body = req.get_json()
        data = body.get("data", [])

        if not data:
            return func.HttpResponse(
                json.dumps({{"error": "No data provided"}}),
                status_code=400, mimetype="application/json"
            )

        df = pd.DataFrame(data)
        predictions = model.predict(df).tolist()

        result = {{"predictions": predictions}}
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(df)
            result["confidence"] = [float(max(p)) for p in proba]

        return func.HttpResponse(
            json.dumps(result),
            status_code=200, mimetype="application/json"
        )
    except Exception as e:
        return func.HttpResponse(
            json.dumps({{"error": str(e)}}),
            status_code=500, mimetype="application/json"
        )

# --- Deployment ---
# 1. func init --python
# 2. Copy this file to your function app
# 3. func azure functionapp publish YOUR_APP_NAME
'''
        return {"code": code, "filename": "predict_function.py", "language": "python"}

    # ── HuggingFace Spaces ─────────────────────────────────────

    @staticmethod
    def _gen_huggingface_spaces(model_format, model_name, task_type, feature_names, target_column, num_features):
        # HuggingFace Spaces uses Gradio or Streamlit
        features = feature_names or [f"feature_{i}" for i in range(num_features or 5)]
        load_code = _get_load_snippet(model_format, model_name)

        inputs_code = ",\n        ".join([
            f'gr.Number(label="{f}")'
            for f in features[:10]
        ])

        code = f'''"""
NeuralForge — HuggingFace Spaces App (Gradio)
Model: {model_name} | Task: {task_type}

Upload this file as app.py to a new HuggingFace Space.
"""

import gradio as gr
import pandas as pd
import numpy as np

{load_code}

model = load_model("model.{model_format}")

def predict({", ".join(features[:10])}):
    """Make a prediction with the trained model."""
    input_data = {{
        {", ".join(f'"{f}": {f}' for f in features[:10])}
    }}
    df = pd.DataFrame([input_data])
    prediction = model.predict(df)[0]

    if hasattr(model, "predict_proba"):
        proba = model.predict_proba(df)[0]
        confidence = float(max(proba)) * 100
        return f"Prediction: {{prediction}}\\nConfidence: {{confidence:.1f}}%"

    return f"Prediction: {{prediction}}"

demo = gr.Interface(
    fn=predict,
    inputs=[
        {inputs_code}
    ],
    outputs=gr.Textbox(label="Prediction"),
    title="🧠 {model_name}",
    description="Powered by NeuralForge AutoML",
    theme="default",
)

if __name__ == "__main__":
    demo.launch()

# --- requirements.txt for HuggingFace Space ---
# gradio
# pandas
# numpy
# scikit-learn
# joblib
# xgboost  (if using XGBoost)
# lightgbm (if using LightGBM)
'''
        return {"code": code, "filename": "app.py", "language": "python"}


# ── Helpers ────────────────────────────────────────────────────

def _get_load_snippet(model_format: str, model_name: str) -> str:
    """Return the appropriate model loading code for a given format and model name."""
    
    # Framework specific override for generic formats like joblib/pkl
    if model_format in ["joblib", "pkl"]:
        name_lower = model_name.lower()
        if "xgboost" in name_lower:
            return "import joblib\nimport xgboost as xgb\n\ndef load_model(path):\n    # Framework: xgb.XGBClassifier() / xgb.XGBRegressor()\n    return joblib.load(path)"
        elif "catboost" in name_lower:
            return "import joblib\nimport catboost\n\ndef load_model(path):\n    # Framework: catboost.CatBoostClassifier() / catboost.CatBoostRegressor()\n    return joblib.load(path)"
        elif "lightgbm" in name_lower:
            return "import joblib\nimport lightgbm as lgb\n\ndef load_model(path):\n    # Framework: lgb.LGBMClassifier() / lgb.LGBMRegressor()\n    return joblib.load(path)"
        elif "neural network" in name_lower or "mlp" in name_lower:
            return "import joblib\nfrom sklearn.neural_network import MLPClassifier\n\ndef load_model(path):\n    # Framework: MLPClassifier()\n    return joblib.load(path)"
            
    snippets = {
        "joblib": "import joblib\n\ndef load_model(path):\n    return joblib.load(path)",
        "pkl": "import pickle\n\ndef load_model(path):\n    with open(path, 'rb') as f:\n        return pickle.load(f)",
        "onnx": "import onnxruntime as rt\nimport numpy as np\n\ndef load_model(path):\n    return rt.InferenceSession(path)",
        "json": "import xgboost as xgb\n\ndef load_model(path):\n    model = xgb.XGBClassifier()\n    model.load_model(path)\n    return model",
        "bst": "import xgboost as xgb\n\ndef load_model(path):\n    model = xgb.XGBClassifier()\n    model.load_model(path)\n    return model",
        "txt": "import lightgbm as lgb\n\ndef load_model(path):\n    return lgb.Booster(model_file=path)",
        "h5": "import tensorflow as tf\nfrom tensorflow import keras\n\ndef load_model(path):\n    # Framework: tf.keras.Sequential(...)\n    return keras.models.load_model(path)",
        "pt": "import torch\nimport torch.nn as nn\n\ndef load_model(path):\n    # Framework: torch.nn.Module\n    return torch.load(path, weights_only=False)",
        "pth": "import torch\nimport torch.nn as nn\n\ndef load_model(path):\n    # Framework: torch.nn.Module\n    return torch.load(path, weights_only=False)",
    }
    return snippets.get(model_format, "import joblib\n\ndef load_model(path):\n    return joblib.load(path)")
